name: github-actions-learn
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 19.9.0
      - name: Install dependecies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test